### ISSUE TITLE
A reference about this source code ?

### ISSUE THREAD

**Issue by haoxiaozi** [autonomous-viranjan/Fast-Data-driven-MPC#1]
Hi, viranjan,
     I'm sorry to trouble you . This source code is in interesting. Could you tell me if there is a paper that can understand the code in more detail?

**Comment by autonomous-viranjan** [comment]
Hi wenqingji,
Thank you for your interest in the code. There are several aspects to this project. If you could share the specific part you might be interested in, I could indeed share some papers. Otherwise, our paper will be online soon, which explains the overall concept in detail.

**Comment by haoxiaozi** [comment]
> Hi wenqingji,
> Thank you for your interest in the code. There are several aspects to this project. If you could share the specific part you might be interested in, I could indeed share some papers. Otherwise, our paper will be online soon, which explains the overall concept in detail.

Hi viranjan, 
Thank you for your help. I'm working on platoon fuel efficient control. I felt that the code implementation of the FMPC control method would be very useful to me, so I wanted to look at the theoretical part of the code implementation. However, if your paper comes online soon, I'll look forward to reading it. Thank you so such.

**Comment by autonomous-viranjan** [comment]
Sure and if you are interested in FMPC, you can definitely follow this link [S. Boyd](https://web.stanford.edu/~boyd/papers/fast_mpc.html) 

Cheers!

**Comment by haoxiaozi** [comment]
> Sure and if you are interested in FMPC, you can definitely follow this link [S. Boyd](https://web.stanford.edu/~boyd/papers/fast_mpc.html)
> 
> Cheers!

Thank you very much !

**Comment by autonomous-viranjan** [comment]
You can now find the preprint of our paper on [ResearchGate](https://www.researchgate.net/). Do cite if you find it useful!

**Comment by haoxiaozi** [comment]
Thanks
